name: Build GTA Custom Online

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Plugin-SDK
      shell: cmd
      run: git clone --depth 1 --recurse-submodules https://github.com/DK22Pac/plugin-sdk.git plugin-sdk

    - name: Inspect Plugin-SDK
      shell: cmd
      run: |
        echo ========================================
        echo PLUGIN-SDK ROOT
        echo ========================================
        dir plugin-sdk

        echo.
        echo ========================================
        echo plugin.h
        echo ========================================
        dir /s /b plugin-sdk\plugin.h

        echo.
        echo ========================================
        echo plugin_sa
        echo ========================================
        dir /s /b plugin-sdk\plugin_sa

        echo.
        echo ========================================
        echo game_sa
        echo ========================================
        dir /s /b plugin-sdk\game_sa

    - name: Configure CMake
      run: cmake -A Win32 -B build

    - name: Build Project
      run: cmake --build build --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Binaries
        path: |
          build/Release/Client.asi
          build/Release/Server.exe
